Data Conversion and Metric Calculation

In [4]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent)) # Project folder

from data_utils import load_companies, load_data, find_project_root

data_path = find_project_root() / "data" / "AssetDB.csv"
companies, df = load_companies(data_path)
print(len(companies), "assets loaded")

54 assets loaded

In [7]:
assetdata = load_data(companies) # Load past 50-day test window

2026-10-12 20:21:28.946692

[*********************100%***********************]  54 of 54 completed

In [16]:
prices = assetdata["Close"] # one column per ticker, one row per trading day
prices = prices.ffill()
prices.tail()

Ticker,AAPL,ABBNE.SW,ABBV,AIR.PA,AMZN,ASML,AZN.L,BA,BAYN.DE,BMW.DE,...,SHEL.L,SIE.DE,SLB,SPY,SU.PA,TTE.PA,URTH,VOW3.DE,VWCE.DE,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2026-10-06,333.630005,82.099998,266.690002,188.000000,256.290009,1834.099976,11958.0,189.820007,44.439999,54.639999,...,3651.0,279.000000,50.000000,779.090027,260.500000,75.720001,209.729996,68.879997,173.559998,164.479996
2026-10-07,336.670013,80.239998,271.359985,187.440002,259.920013,1804.959961,12180.0,188.320007,43.970001,53.660000,...,3648.0,271.200012,47.959999,777.219971,254.550003,75.419998,208.669998,69.739998,172.919998,164.050003
2026-10-08,340.420013,79.040001,272.420013,187.259995,254.059998,1769.790039,11892.0,187.750000,42.590000,52.180000,...,3780.5,264.250000,48.980000,773.929993,261.100006,77.580002,207.869995,66.599998,171.899994,168.500000
2026-10-09,336.640015,79.480003,276.470001,187.800003,262.429993,1780.339966,11998.0,190.369995,43.770000,53.259998,...,3793.5,272.100006,48.950001,778.570007,266.399994,78.529999,209.139999,68.000000,172.860001,168.940002
2026-10-12,340.375000,80.239998,280.214996,188.139999,259.540009,1759.780029,12026.0,189.774994,43.830002,53.060001,...,3836.0,275.750000,48.615002,777.380005,265.350006,78.980003,208.824997,68.400002,173.479996,172.000000

In [17]:
returns = prices.pct_change().dropna(how="all")
returns.tail()

Ticker,AAPL,ABBNE.SW,ABBV,AIR.PA,AMZN,ASML,AZN.L,BA,BAYN.DE,BMW.DE,...,SHEL.L,SIE.DE,SLB,SPY,SU.PA,TTE.PA,URTH,VOW3.DE,VWCE.DE,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2026-10-06,0.002223,-0.000487,0.003499,-0.005712,0.019451,-0.013851,0.016491,-0.015048,0.010919,0.007746,...,0.005370,0.014545,-0.005569,0.005498,-0.045088,-0.001055,0.005658,0.004961,0.003817,0.002927
2026-10-07,0.009112,-0.022655,0.017511,-0.002979,0.014164,-0.015888,0.018565,-0.007902,-0.010576,-0.017936,...,-0.000822,-0.027957,-0.040800,-0.002400,-0.022841,-0.003962,-0.005054,0.012485,-0.003687,-0.002614
2026-10-08,0.011139,-0.014955,0.003906,-0.000960,-0.022545,-0.019485,-0.023645,-0.003027,-0.031385,-0.027581,...,0.036321,-0.025627,0.021268,-0.004233,0.025732,0.028640,-0.003834,-0.045024,-0.005899,0.027126
2026-10-09,-0.011104,0.005567,0.014867,0.002884,0.032945,0.005961,0.008914,0.013955,0.027706,0.020698,...,0.003439,0.029707,-0.000612,0.005995,0.020299,0.012245,0.006110,0.021021,0.005585,0.002611
2026-10-12,0.011095,0.009562,0.013546,0.001810,-0.011012,-0.011548,0.002334,-0.003125,0.001371,-0.003755,...,0.011203,0.013414,-0.006844,-0.001528,-0.003941,0.005730,-0.001506,0.005882,0.003587,0.018113

Debugging cell for NaN values

In [18]:
print(prices.shape) # (trading days, tickers)
print(prices.isna().sum().sort_values(ascending=False).head(10))

print(prices.isna().sum().value_counts())
prices[prices.isna().any(axis=1)]

print(prices.isna().sum().sum())
print(returns.shape)

(36, 54)
Ticker
AAPL        0
ABBNE.SW    0
ABBV        0
AIR.PA      0
AMZN        0
ASML        0
AZN.L       0
BA          0
BAYN.DE     0
BMW.DE      0
dtype: int64
0    54
Name: count, dtype: int64
0
(35, 54)